server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
    max-threads: 500
  servlet:
    context-path: /test
  max-http-header-size: 4048576

spring:
  application:
    name: localtest #服务名称
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#mybatis-plus:
#  mapper-locations: classpath:mapper/*Mapper.xml


#附件下载
ftpServer:
  #IP|端口|用户名|密码|远程路径|ftp类型
  maps: "{
         	Q: '192.168.30.118|21|root|root|/var/ftp|ftp',
         	Q1: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Q2: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
            X: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Z1: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Z2: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Z: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	U: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	U0: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	V: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Y: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp'
         }"
  saveDir: contact
